version: '3'

services:
  service_registry:
    build:
      context: .
      dockerfile: DockerfileServiceRegistry
    hostname: my-registry
    ports:
      - "8888:8888"

  peer:
    build:
      context: .
      dockerfile: DockerfilePeer
    hostname: peer
    ports:
     - ":30000"
    depends_on:
      - service_registry
    links:
      - service_registry
    deploy:
      replicas: 8